### ISSUE TITLE
Panic on optional TLS settings

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/telemetry-manager#1192]
**Description**

With current version 1.18.0 of telemetry-manager a panic is observed on metricpipelines having no TLS settings defined:

```
panic: runtime error: invalid memory address or nil pointer dereference
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1630bb8]

goroutine 601 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.4/pkg/internal/controller/controller.go:111 +0x1e5
panic({0x18312c0?, 0x2a077e0?})
	/usr/local/go/src/runtime/panic.go:770 +0x132
github.com/kyma-project/telemetry-manager/internal/tlscert.(*Validator).Validate(0xc000513080, {0x1d08298, 0xc001683920}, {0xc001c02108?, 0xc001c02120?, 0x0?})
	/telemetry-manager-workspace/internal/tlscert/tls_cert_validator.go:112 +0x118
github.com/kyma-project/telemetry-manager/internal/reconciler/logpipeline.(*Reconciler).evaluateConfigGeneratedCondition(0xc0002a9708, {0x1d08298, 0xc001683920}, 0xc00189c000)
	/telemetry-manager-workspace/internal/reconciler/logpipeline/status.go:119 +0x1e4
github.com/kyma-project/telemetry-manager/internal/reconciler/logpipeline.(*Reconciler).setFluentBitConfigGeneratedCondition(0x0?, {0x1d08298?, 0xc001683920?}, 0xc00189c000)
	/telemetry-manager-workspace/internal/reconciler/logpipeline/status.go:90 +0x37
github.com/kyma-project/telemetry-manager/internal/reconciler/logpipeline.(*Reconciler).updateStatus(0xc0002a9708, {0x1d08298, 0xc001683920}, {0xc0007658dc, 0x3})
	/telemetry-manager-workspace/internal/reconciler/logpipeline/status.go:41 +0x139
github.com/kyma-project/telemetry-manager/internal/reconciler/logpipeline.(*Reconciler).doReconcile.func1()
	/telemetry-manager-workspace/internal/reconciler/logpipeline/reconciler.go:143 +0x38
panic({0x18312c0?, 0x2a077e0?})
	/usr/local/go/src/runtime/panic.go:770 +0x132
github.com/kyma-project/telemetry-manager/internal/tlscert.(*Validator).Validate(0xc000513080, {0x1d08298, 0xc001683920}, {0xc001d5e270?, 0xc001d5e288?, 0x0?})
	/telemetry-manager-workspace/internal/tlscert/tls_cert_validator.go:112 +0x118
github.com/kyma-project/telemetry-manager/internal/reconciler/logpipeline.(*Reconciler).isReconcilable(0xc0002a9708, {0x1d08298, 0xc001683920}, 0xc0002fc008)
	/telemetry-manager-workspace/internal/reconciler/logpipeline/reconciler.go:322 +0x16d
github.com/kyma-project/telemetry-manager/internal/reconciler/logpipeline.(*Reconciler).getReconcilablePipelines(0xc0002a9708, {0x1d08298, 0xc001683920}, {0xc0002fc008, 0x2, 0x0?})
	/telemetry-manager-workspace/internal/reconciler/logpipeline/reconciler.go:295 +0xbc
github.com/kyma-project/telemetry-manager/internal/reconciler/logpipeline.(*Reconciler).doReconcile(0xc0002a9708, {0x1d08298, 0xc001683920}, 0xc001685a00)
	/telemetry-manager-workspace/internal/reconciler/logpipeline/reconciler.go:165 +0x29a
github.com/kyma-project/telemetry-manager/internal/reconciler/logpipeline.(*Reconciler).Reconcile(0xc0002a9708, {0x1d08298, 0xc001683920}, {{{0x0?, 0x0?}, {0xc0007658dc?, 0x5?}}})
	/telemetry-manager-workspace/internal/reconciler/logpipeline/reconciler.go:137 +0x1a5
github.com/kyma-project/telemetry-manager/controllers/telemetry.(*LogPipelineController).Reconcile(0xc000d62c00?, {0x1d08298?, 0xc001683920?}, {{{0x0?, 0x5?}, {0xc0007658dc?, 0xc0007c9d10?}}})
	/telemetry-manager-workspace/controllers/telemetry/logpipeline_controller.go:53 +0x2b
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x1d0c178?, {0x1d08298?, 0xc001683920?}, {{{0x0?, 0xb?}, {0xc0007658dc?, 0x0?}}})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.4/pkg/internal/controller/controller.go:114 +0xb7
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc00035a370, {0x1d082d0, 0xc00051b040}, {0x18b9180, 0xc000518420})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.4/pkg/internal/controller/controller.go:311 +0x3bc
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc00035a370, {0x1d082d0, 0xc00051b040})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.4/pkg/internal/controller/controller.go:261 +0x1be
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.4/pkg/internal/controller/controller.go:222 +0x79
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2 in goroutine 116
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.4/pkg/internal/controller/controller.go:218 +0x486
```

```yaml
spec:
  input:
    istio:
      enabled: false
    prometheus:
      enabled: false
      namespaces:
        exclude:
        - kyma-system
        - kube-system
        - istio-system
        - compass-system
    runtime:
      enabled: true
      namespaces:
        include:
        - cap
  output:
    otlp:
      endpoint:
        value: http://my-destination.my-namespace.svc.cluster.local:4317
      protocol: grpc
```

**Expected result**
No crashloop

**Actual result**
A crashloop of manager pod

**Steps to reproduce**

**Troubleshooting**

**Release Notes**

```

```

**Comment by a-thaler** [comment]
Backport to 1.18.1 is still missing

**Comment by TeodorSAP** [comment]
Backport done
